version: '2'
services:
  sn-db:
    image: mariadb:10.5.4
    container_name: sn-db
    network_mode: "bridge"
    environment:
      MYSQL_ROOT_PASSWORD: ${LCOSNDBROOTPASS:-password}
    volumes:
    - ${LCOSNDBPATH:-mysql}:/var/lib/mysql
  lcosnpipe:
    image: ${SNPIPEDOCKER_IMG:-lcogtsnpipe:latest}
    network_mode: "bridge"
    container_name: lcosnpipe
    mem_limit: '8g'
    environment:
      LCOSNDBHOST: ${LCOSNDBHOST:-supernovadb}
      LCOSNDBNAME: ${LCOSNDBNAME:-supernova}
      LCOSNDBUSER: ${LCOSNDBUSER:-supernova}
      LCOSNDBPASS: ${LCOSNDBPASS:-''}
    links:
      - sn-db:supernovadb
